/*
** ###################################################################
**     This code is generated by the Device Initialization Tool.
**     It is overwritten during code generation.
**     USER MODIFICATION ARE NOT PRESERVED IN THIS FILE.
**
**     Project   : Driver
**     Processor : MC9S08AW60CFU
**     Version   : Bean 01.130, Driver 01.03, CPU db: 2.87.181
**     Datasheet : MC9S08AW60 Rev 2 12/2006
**     Date/Time : 05/11/2007, 12.46
**     Abstract  :
**         This module contains device initialization code
**         for selected on-chip peripherals.
**     Contents  :
**         Function "MCU_init" initializes selected peripherals
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2006
**     UNIS, spol s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################
*/

#ifndef __Driver_H
#define __Driver_H 1

/* Include shared modules, which are used for whole project */

extern void MCU_init(void);

__interrupt void isrVkeyboard1(void);
__interrupt void isrVsci1tx(void);
__interrupt void isrVsci1rx(void);
__interrupt void isrVsci1err(void);
__interrupt void isrVsci2tx(void);
__interrupt void isrVsci2rx(void);
__interrupt void isrVsci2err(void);
__interrupt void isrVtpm2ovf(void);
__interrupt void Timer_2milli(void);
__interrupt void isrVicg(void);
__interrupt void isrVirq(void);
//__interrupt void isrVsci2tx(void);


/* END Driver */

#endif
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.00 [03.89]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/

