extern void JD_TX_Managment(void);
extern void LoadJD_Menu(uchar subitemsel);
extern void LoadJD_SleepMenu(uchar subitemsel);
extern void SetSwitchIcon(uchar subitemsel,uchar data1, uchar data2,uchar data3,uchar data4,uchar data5);
//extern void sendJDdata(uchar JDcmd,uchar JDpage,uchar JDlen, uchar *p);
extern void SetButton_State( uchar data1, uchar data2,uchar data3,uchar data4);
extern void SetControl_State( uchar data1, uchar data2,uchar data3);
extern void ScenarioShortcut_Init(void);
extern void HomeHA_RoomTitle_Init(uchar room);
extern unsigned int FloatToInt(unsigned long data);
extern uchar IntToFloat(unsigned int data);
extern void POP_JD_Command(void);
extern void SetTel_Num(uchar Menu_ID, uchar Control_ID,uchar Num_Len, uchar *T_num);
extern void CheckCommand(unsigned int p);
extern uchar IfBelongType(uchar type,uchar Filter_Type);
extern void AC_Menu_Init(uchar AC_menu);
extern void HA_Button_Name(void);
extern void HA_Button_Name_Filter(void);
extern void RoomType_Init(uchar ch,uchar w_i);
extern void TimerEventSetting_Init(uchar item);
extern void UpdataStatusHomeHA_RoomButtonWithFilter_Init(uchar room, uchar index, uchar Filter, uchar T_Room, uchar T_index);
extern void TimerEventFlag_Init(void);
extern void ShowTelNum(void);
extern void Tel_MemoryName_Init(void);
extern void RoomType_Init_Back(void);
extern void RoomType_Init_Back0(void);
extern void ScenarioMenu_Init(uchar ch, uchar w_i);
extern void ScenarioShortcut_Init(void);
extern void JD_CallBack(void);
extern void SetMainMenuState(unsigned char ID,unsigned char St);
extern void Setting_Menu(void);
extern void SetDate(void);
extern void Set_Oclock( uchar data1, uchar data2,uchar data3,uchar data4, uchar data5, uchar data6);
extern void CallcodeInputMenu_Init(uchar index);
extern void ShowInterCom_PhoneBook(uchar index);
extern void FillEdit_Name_Code_Type(uchar PageIndex,uchar Index);
extern void CallType_SetFocus(uchar index);
extern void ShowPhoneBook_E_D(uchar p);
extern void Init_VolumeBar(uchar menu_id);
extern void SetAudio(void);
extern void If_need_Wakeup_LCD(void);
extern void AlarmSystemZoneName_Init(void);
extern void HomeHA_RoomButtonWithFilter_Init(uchar room, uchar index, uchar Filter);
extern void Object_Button_Visible(void);
extern uchar HomeHA_RoomButtonWithFilter_Check(uchar room, uchar Filter);
extern void Init_AC_Temperature(uchar p);
extern void Init_AC_CH(uchar menu_id);
extern void Init_AC_mode(uchar menu_id);
extern void Init_AC_Speed(uchar menu_id);
extern void Init_AC_Swing(uchar menu_id);
extern void Init_HVAC_CH(uchar menu_id);
extern void Init_HVAC_Speed(uchar menu_id);
extern void CCTV_Init(void);
extern void AlarmStatus_Name_Init(uchar menuid);
extern void CheckDel_Name_Code_Type(uchar PageIndex,uchar Index);
extern void If_need_Wakeup_LCD_CallBack(void);
